import { mkdirSync } from 'node:fs';
import { dirname } from 'node:path';
import { DatabaseSync } from 'node:sqlite';
import type { AuditEvent, Suggestion, SupportCase } from './types.js';

export class InvalidCaseStateError extends Error {}

export class AppDb {
  private db: DatabaseSync;

  constructor(path: string) {
    if (path !== ':memory:') mkdirSync(dirname(path), { recursive: true });
    this.db = new DatabaseSync(path);
    this.db.exec(`
      PRAGMA foreign_keys = ON;
      CREATE TABLE IF NOT EXISTS cases (id INTEGER PRIMARY KEY, subject TEXT NOT NULL, customer_email TEXT NOT NULL, description TEXT NOT NULL, status TEXT NOT NULL, created_at TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS ai_runs (id INTEGER PRIMARY KEY, case_id INTEGER NOT NULL, suggestion_json TEXT NOT NULL, provider TEXT NOT NULL, created_at TEXT NOT NULL, FOREIGN KEY(case_id) REFERENCES cases(id));
      CREATE TABLE IF NOT EXISTS approvals (id INTEGER PRIMARY KEY, case_id INTEGER NOT NULL, decision TEXT NOT NULL, note TEXT, created_at TEXT NOT NULL, FOREIGN KEY(case_id) REFERENCES cases(id));
      CREATE TABLE IF NOT EXISTS audit_events (id INTEGER PRIMARY KEY, case_id INTEGER NOT NULL, event_type TEXT NOT NULL, detail TEXT NOT NULL, created_at TEXT NOT NULL, FOREIGN KEY(case_id) REFERENCES cases(id));
    `);
  }

  private now(): string {
    return new Date().toISOString();
  }

  private transaction<T>(operation: () => T): T {
    this.db.exec('BEGIN');
    try {
      const result = operation();
      this.db.exec('COMMIT');
      return result;
    } catch (error) {
      this.db.exec('ROLLBACK');
      throw error;
    }
  }

  private audit(caseId: number, eventType: string, detail: string): void {
    this.db.prepare(`
      INSERT INTO audit_events (case_id, event_type, detail, created_at)
      VALUES (?, ?, ?, ?)
    `).run(caseId, eventType, detail, this.now());
  }

  createCase(input: Pick<SupportCase, 'subject' | 'customerEmail' | 'description'>): SupportCase {
    return this.transaction(() => {
      const result = this.db.prepare(`
        INSERT INTO cases (subject, customer_email, description, status, created_at)
        VALUES (?, ?, ?, ?, ?)
      `).run(input.subject, input.customerEmail, input.description, 'open', this.now());
      const id = Number(result.lastInsertRowid);
      this.audit(id, 'case.created', 'Support case created');
      return this.getCase(id)!;
    });
  }

  listCases(): SupportCase[] {
    return this.db.prepare(`
      SELECT id, subject, customer_email AS customerEmail, description, status, created_at AS createdAt
      FROM cases ORDER BY id DESC
    `).all() as unknown as SupportCase[];
  }

  getCase(id: number): SupportCase | undefined {
    return this.db.prepare(`
      SELECT id, subject, customer_email AS customerEmail, description, status, created_at AS createdAt
      FROM cases WHERE id = ?
    `).get(id) as SupportCase | undefined;
  }

  saveSuggestion(id: number, suggestion: Suggestion, provider: string): void {
    this.transaction(() => {
      const supportCase = this.getCase(id);
      if (!supportCase) throw new Error('Case not found');
      if (supportCase.status !== 'open') throw new InvalidCaseStateError('Case is not open');

      this.db.prepare(`
        INSERT INTO ai_runs (case_id, suggestion_json, provider, created_at)
        VALUES (?, ?, ?, ?)
      `).run(id, JSON.stringify(suggestion), provider, this.now());
      this.db.prepare('UPDATE cases SET status = ? WHERE id = ?').run('awaiting_approval', id);
      this.audit(id, 'ai.suggestion_created', `AI suggestion generated by ${provider}`);
    });
  }

  latestSuggestion(id: number) {
    const row = this.db.prepare(`
      SELECT id, suggestion_json AS suggestionJson, provider, created_at AS createdAt
      FROM ai_runs WHERE case_id = ? ORDER BY id DESC LIMIT 1
    `).get(id) as { id: number; suggestionJson: string; provider: string; createdAt: string } | undefined;
    return row && { ...row, suggestion: JSON.parse(row.suggestionJson) as Suggestion };
  }

  decide(id: number, decision: 'approved' | 'rejected', note?: string): SupportCase | undefined {
    return this.transaction(() => {
      const supportCase = this.getCase(id);
      if (!supportCase) return undefined;
      if (supportCase.status !== 'awaiting_approval') {
        throw new InvalidCaseStateError('Case is not awaiting approval');
      }
      this.db.prepare(`
        INSERT INTO approvals (case_id, decision, note, created_at)
        VALUES (?, ?, ?, ?)
      `).run(id, decision, note ?? null, this.now());
      this.db.prepare('UPDATE cases SET status = ? WHERE id = ?').run(decision, id);
      this.audit(id, `approval.${decision}`, `Human ${decision}${note ? `: ${note}` : ''}`);
      return this.getCase(id)!;
    });
  }

  timeline(id: number): AuditEvent[] {
    return this.db.prepare(`
      SELECT id, event_type AS eventType, detail, created_at AS createdAt
      FROM audit_events WHERE case_id = ? ORDER BY id ASC
    `).all(id) as unknown as AuditEvent[];
  }

  close(): void {
    this.db.close();
  }
}
